on:
  workflow_call:
    inputs:
      config:
        description: "the relative path to the config file"
        default: renovate.json
        type: string

jobs:
  validator:
    runs-on: ubuntu-latest
    # https://github.com/renovatebot/docker-renovate
    container:
      image: renovate/renovate-slim
      volumes:
        - ${{ inputs.config }}:/home/ubuntu/inputs.config.json
    steps:
      - run: renovate-config-validator /home/ubuntu/inputs.config.json
