name: "bettermarks/renovate-config/validator"
description: "validates a renavate config"
inputs:
  config:
    description: "the relative path to the config file"
    default: renovate.json

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
      with:
        repository: "bettermarks/renovate-config"
        path: renovate-config
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
    - run: ./renovate-config/validate.sh ${{ inputs.config }}
      shell: bash
