name: "bettermarks/renovate-config/validator"
description: "validates a renavate config"
inputs:
  config:
    description: "the relative path to the config file"
    default: renovate.json

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
      with:
        repository: "bettermarks/renovate-config"
        path: renovate-config
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
      with:
        cache: pnpm

    - name: validate config file
      # no need to run the ./validate.sh script since we have configured pnpm and node and it's much faster this way
      run: pnpm dlx --package renovate renovate-config-validator --strict "${{ inputs.config }}"
      shell: bash
