name: "bettermarks/renovate-config/validator"
description: "validates a renavate config"
inputs:
  config:
    description: "the relative path to the config file"
    default: renovate.json

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
    - run: ./validate.sh ${{ inputs.config }}
      shell: bash
